MdPages/urls.py
from . import views
from django.urls import path
app_name = 'MdPages'
urlpatterns = [
    path('<page_name>', views.page, name='page')
]

download/urls.py
from . import views
from django.urls import path
app_name = 'download'
urlpatterns = [
    path('<tag>/', views.release, name='release'),
    path('', views.releases, name='releases'),
    path('clear_cache', views.clear_cache, name='clear_cache'),
]

main/urls.py
from . import views
from django.urls import path
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('contract/', views.contract, name='contract'),
]

rscraftsite_v2/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from . import settings
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('releases/', include('download.urls')),
    path('pages/', include('MdPages.urls')),
    path('votes/', include('vote.urls')),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

vote/urls.py
from . import views
from django.urls import path
app_name = 'votes'
urlpatterns = [
    path('<vote_name>/', views.vote_page, name='vote'),
    path('', views.vote_list, name='votes'),
    path('<vote_name>/<select_id>', views.submit, name='vote_selected')
]

MdPages/models.py
from django.db import models

# Create your models here.
class MarkdownFile(models.Model):
    page_name = models.CharField(max_length=100)
    file_path = models.FileField(upload_to='markdown_files/')

download/models.py
from django.db import models

# Create your models here.
class Version(models.Model):
    tag = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    github_release = models.URLField()
    github_download_link = models.URLField()
    lanzou_url = models.URLField()
    
    def __str__(self):
        return self.tag + " - " + self.title
    
    def get_description(self):
        return self.description[:100].replace("\\n", " ") + "..."
    
class Backup(models.Model):
    backup_time = models.DateTimeField(auto_now_add=True)
    api_response = models.TextField()

vote/models.py
from django.db import models

# Create your models here.
class Vote(models.Model):
    name = models.CharField(max_length=100)
    vts_file = models.FileField(upload_to='vts_files/')

MdPages/views.py
from django.shortcuts import render
from .models import MarkdownFile
# Create your views here.
def page(request, page_name):
    selected_page = MarkdownFile.objects.get(page_name=page_name)
    file_content = selected_page.file_path.read().decode('utf-8')
    #file_content = file_content.replace('\r\n', '<p></p>')
    return render(request, 'pages/page.html', {'page_name': page_name, 'file_content': file_content})

download/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required
from .models import Version, Backup
from django.utils import timezone
from . import backup
import time

def releases(request):
    # 如果Backup为空或者最新的Backup距离现在大于5分钟，备份
    if Backup.objects.count() == 0 or (time.time() - Backup.objects.last().backup_time.timestamp() > 300):
        backup.get_release_info()
        Backup.objects.create(
            # 创建Backup的时间
            backup_time=timezone.now(),
            # 获取API响应
            api_response=backup.get_release_info(),
        )
    versions = Version.objects.all()
    for ver in versions:
        ver.description = ver.get_description()
    return render(request, 'download/releases.html', {'versions': versions})

def release(request, tag):
    target_ver = Version.objects.get(tag=tag)
    return render(request, 'download/release.html', {'target_ver': target_ver})
# 只有管理员可以访问
@permission_required('download.clear_cache')
def clear_cache(request):
    Backup.objects.all().delete()
    return redirect('download:releases')

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'main/index.html')

def contract(request):
    return render(request, 'main/contract.html')

vote/views.py
from django.shortcuts import render
from models import Vote
# Create your views here.
def vote_page(request, vote_name):
    """
    By gene-2012
    """
    vote_obj = Vote.objects.get(name=vote_name)
    vote_vts = vote_obj.vts_file.read().decode('utf-8')
    render(request, 'voteInfo.html', {'vote_obj' : vote_obj, 'vote_vts' : vote_vts})

MdPages/templates/pages/markdown_render.html
<div id="source-code" style="display: none;">{{ file_content | safe}}</div>
<div id="content"></div>
<script>
    var textContent = $('#source-code').text();
    document.getElementById('content').innerHTML =
    marked.parse(textContent, {breaks: true});
    hljs.highlightAll();
</script>

MdPages/templates/pages/page.html
{% extends "main/base.html" %}
{% block title %}Page {{page_name}}{% endblock title %}
{% block content %}
{% include "pages/markdown_render.html" %}
{% endblock content %}

download/templates/download/release.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}Release - {{target_ver.tag}}{% endblock title %}
{% block content %}
<h1> {{target_ver.tag}} {{target_ver.title}}</h1>
<hr />
<div id="source-code" style="display: none;">{{ target_ver.description | safe}}</div>
<div id="content"></div>
{% if target_ver.description %}
    {% include "pages/markdown_render.html" %}
{% else %}
    <div class="alert alert-warning" role="alert">
        No description available.
    </div>
{% endif %}
<hr />
{% if target_ver.github_release %}
<a href="{{ target_ver.github_release }}" class="download-link github-download">View Release on Github</a>
<a href="{{ target_ver.github_download_link }}" class="download-link github-download">Download From Github</a>
{% endif %}
{% if target_ver.lanzou_url %}
<a href="{{ target_ver.lanzou_url }}" class="download-link lanzou-download">Download From Lanzou</a>
{% endif %}
{% endblock content %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/release.css' %}">
{% endblock extra_css %}
{% block extra_js %}
<script>
    document.getElementById('download').classList.add('active');
</script>
{% endblock extra_js %}

download/templates/download/releases.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Download{% endblock title %}

{% block content %}
    <div class="container">
        <h1 class="my-4 text-center">Releases</h1>
        <!--只有用户是管理员时显示清空缓存按钮-->
        {% if user.is_superuser %}
            <a href="{% url 'download:clear_cache' %}" class="btn btn-danger"> Clear Cache & Refresh</a>
        {% endif %}
        <hr />
        {% if versions %}
            <div class="list-group">
                {% for version in versions %}
                    <a href="{% url 'download:release' version.tag %}" class="list-group-item list-group-item-action flex-column align-items-start" name="{{version.tag}}">
                        <div>
                            <h5 class="mb-1 d-inline-block">{{version.tag}}</h5>
                            <strong class="text-primary ms-2">{{version.title}}</strong> <!-- 修改这一行 -->
                        </div>
                        <p class="mb-1">{{version.description|truncatewords:10}}</p>
                        <small>{{version.release_date|date:"F j, Y"}}</small>
                    </a>
                    <hr />
                {% empty %}
                    <div class="alert alert-info" role="alert">
                        No releases available.
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="alert alert-danger" role="alert">
                An error occurred while fetching releases.
            </div>
        {% endif %}
    </div>
{% endblock content %}
{% block extra_js %}
    <script>
        document.getElementById('download').classList.add('active');
    </script>
{% endblock extra_js %}

main/templates/main/base.html
<!-- myapp/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Redstone Craft（红石工艺）{% endblock title %}</title>
    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="icon" href="{% static 'rsclogo.png' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/global.css' %}" />
    <link rel="stylesheet" href="{% static 'css/github.min.css' %}" />
    {% block extra_css %}
    {% endblock extra_css %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/marked.min.js' %}"></script>
    <script src="{% static 'js/highlight.min.js' %}"></script>
    {% block extra_js %}
    {% endblock extra_js %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'main:index' %}"><img src="{% static 'rsclogo.png' %}" class="logo"/> Redstone Craft（红石工艺）</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item" id="home">
                    <a class="nav-link" href="{% url 'main:index' %}">Home</a>
                </li>
                <li class="nav-item" id="download">
                    <a class="nav-link" href="{% url 'download:releases' %}">Download</a>
                </li>
                <li class="nav-item" id="contact">
                    <a class="nav-link" href="{% url 'main:contract' %}">Contact</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        {% block content %}
        {% endblock content %}
    </div>

</body>
</html>

main/templates/main/contract.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}Contact Us{% endblock title %}
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3>Contact Information</h3>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item"><strong>QQ Group:</strong> <a href="https://qm.qq.com/q/dUT6HQZnnW"> 688022488 </a></li>
                        <li class="list-group-item"><strong>Github:</strong> <a href="https://www.github.com/RedstoneCraftTeam/Redstone_Craft/"> @RedstoneCraftTeam </a></li>
                        <li class="list-group-item"><strong>E-mail:</strong> <a href="mailto:info@geneluo.site"> info@geneluo.site </a></li>
                        <li class="list-group-item"><strong>Weibo:</strong> <a href="https://weibo.com/u/7764949880"> @红石工艺RedstoneCraft </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!--显示sponsor.jpg-->
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3>赞助我们</h3>
                </div>
                <div class="card-body">
                    <img src="{% static 'images/sponsor.jpg' %}" alt="赞助" style="width: 100%;" />
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block extra_js %}
    <script>
        document.getElementById('contact').classList.set('nav-item active');
    </script>
{% endblock extra_js %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content %}
    <!-- Banner区域，占据页面上半部分 -->
    <div class="banner">
        <strong>
            <h1> 红石工艺（Redstone Craft） </h1>
            <h3> 轻量 纯净 国创 养老 原版 </h3>
        </strong>
    </div>

    <!-- Grid布局内容 -->
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4">
                <div class="text-center py-3">
                    <h3>轻量</h3>
                    <p>我们坚持以最少的mod和材质包，换来更好的游戏体验。</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-center py-3">
                    <h3>简洁</h3>
                    <p>我们不想让一个整合包玩起来很麻烦。<br>我们争取让这个整合包在使用上更简单，易入手。</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-center py-3">
                    <h3>单人</h3>
                    <p>就如这个词所说...这个材质包更适合单人游玩！<br>当然，多人游玩也应该毫无问题。<br>（⚠注意：多人游戏中，Tweakeroo模组和X-Ray透视矿材质包慎用，因为有几率会被服务器ban！）</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

vote/templates/voteInfo.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}Vote {{}}{% endblock title %}
{% block content %}
<div id="source-code" style="display: none;">{{ vote_vts | safe}}</div>
<div id="content"></div>
<script>
    var sc = document.getElementById('source-code').innerHTML;
    document.getElementById('content') = marked.parse(sc, {'break': true});
    // 处理投票
    // Format: ::[type] sth. ::end
    var vote_re = /::(.*?) (.*?) ::end/g;
    // 我在看mdn看看怎么解析（好久没碰纯前端了 我永远不想碰前端/运维  
    const vote_list = document.querySelectorAll('#content>ol>li');
    vote_list.forEach((val, key) => {
        // 投票项解析
        switch(val.innerHTML.match(vote_re)[0]){
            case '::radio':
                makeVoteItem(key, val, 0)
                break
            case '::checkbox':
                makeVoteItem(key, val, 1)
                break
        }
    })

    function makeVoteItem(index = 0, element = new Element(), type = 0 | 1){
        element.setAttribute('data-vote-id', index.toString())
        const voteAnswers = element.children
        voteAnswers.
    }
</script>
{% endblock content %}